### ISSUE TITLE
Can`t working request.

### ISSUE THREAD

**Issue by PosReadyNT** [AlekseyZz/aiontai#2]
Hi, I have error `AttributeError: 'ClientResponse' object has no attribute 'ok'` How to fix this problem? 
![screen](https://user-images.githubusercontent.com/66481983/113681758-04eb7780-96cb-11eb-92ae-c23faa4713c7.png)

**Comment by AlekseyZz** [comment]
Have you installed requirements for package?

**Comment by PosReadyNT** [comment]
yeah, aiontai installed packages
![image](https://user-images.githubusercontent.com/66481983/113681936-3ebc7e00-96cb-11eb-8fae-62d366245d0f.png)

**Comment by PosReadyNT** [comment]
I fix it from uninstall requests and install it in aiontai.
